# Generated by Django 6.0.2 on 2026-02-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expertisecategory_expertiseskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('email', models.EmailField(default='gullchaman.bd@gmail.com', max_length=254)),
                ('location', models.CharField(default='Global / Remote', max_length=200)),
                ('phone', models.CharField(default='+92 333 7485759', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
